#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/bevformer_shifted_real_data_results.txt --results_b result_paths/bevformer_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/bevformer/shifted/per_sample --output_file result_paths/bevformer_agreement_shifted_output_files.txt --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/bevformer_shifted_real_data_results.txt --results_b result_paths/bevformer_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/bevformer/shifted/all --output_file result_paths/bevformer_agreement_shifted_output_files.txt --aggregate_all --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/bevformer_shifted_real_data_results.txt --results_b result_paths/bevformer_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/bevformer/shifted/per_scene --output_file result_paths/bevformer_agreement_shifted_output_files.txt --aggregate_per_scene --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json

#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/petr_shifted_real_data_results.txt --results_b result_paths/petr_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/petr/shifted/per_sample --output_file result_paths/petr_agreement_shifted_output_files.txt --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/petr_shifted_real_data_results.txt --results_b result_paths/petr_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/petr/shifted/all --output_file result_paths/petr_agreement_shifted_output_files.txt --aggregate_all --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/petr_shifted_real_data_results.txt --results_b result_paths/petr_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/petr/shifted/per_scene --output_file result_paths/petr_agreement_shifted_output_files.txt --aggregate_per_scene --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json

#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/fcos3d_shifted_real_data_results.txt --results_b result_paths/fcos3d_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/fcos3d/shifted/per_sample --output_file result_paths/fcos3d_agreement_shifted_output_files.txt --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/fcos3d_shifted_real_data_results.txt --results_b result_paths/fcos3d_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/fcos3d/shifted/all --output_file result_paths/fcos3d_agreement_shifted_output_files.txt --aggregate_all --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
#sbatch scripts/berzelius.sh python detection_agreement.py --results_a result_paths/fcos3d_shifted_real_data_results.txt --results_b result_paths/fcos3d_all_shifts.txt --data_root /proj/adas-data/data/nuscenes --output_dir outputs/detection_agreement/fcos3d/shifted/per_scene --output_file result_paths/fcos3d_agreement_shifted_output_files.txt --aggregate_per_scene --dist_ths 2.0 --nusc2nerf_transformations aggregated_dataparser_transforms.json
